name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Conan
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install conan

        conan profile detect --force
        conan install ./ --output-folder=build --build=missing --settings=build_type=Debug

    - name: Compile
      shell: bash
      run: |

        SRC_FOLDER=$(pwd)/src

        echo "Running command: cmake -DRUN_COVERAGE=1 .. && make -j2"

        cd build
        cmake .. -DCMAKE_TOOLCHAIN_FILE=./build/Debug/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_COVERAGE=1 -DENABLE_CJSON_TEST=OFF
        make -j2
